name: Monthly Ride Summary

on:
  schedule:
    # Runs every 5 minutes (ONLY FOR TESTING!)
    - cron: '0 19 28-31 * *'
  
  workflow_dispatch:

jobs:
  send-summary:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: Show current UTC time
        run: date -u

      - name: Install dependencies
        run: |
          pip install notion-client
      
      - name: Send monthly summary
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python send_summary.py
